global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          service: "prometheus"

  - job_name: "alloy"
    metrics_path: /metrics
    static_configs:
      - targets: ["alloy:12345"]
        labels:
          service: "alloy"

  - job_name: "tempo"
    metrics_path: /metrics
    static_configs:
      - targets: [ "tempo:3200" ]
        labels:
          service: "tempo"

  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: [ "loki:3100" ]
        labels:
          service: "loki"

  - job_name: "grafana"
    metrics_path: /metrics
    static_configs:
      - targets: [ "grafana:3000" ]